import RPi.GPIO as GPIO

GPIO_PINS = {
    "DISPENSER_MOTOR": 14,
    "DISPENSER_SENSOR": 12,
    "DISPENSER_LOW": 4,

    "MUNCHER_MOTOR": 15,
    "MUNCHER_SENSOR": 27,
    "MUNCHER_LOW": 22,

    "INSERTER_SENSOR": 6,

    "MUNCH_LED": 5,
    "DISPENSER_LED": 24,
    "CHANGE_LED": 23,

    "COIN_ACCEPTOR_POWER": 18
}

GPIO_OUTPUTS = {
    "DISPENSER_MOTOR",
    "MUNCHER_MOTOR",
    "MUNCH_LED",
    "DISPENSER_LED",
    "CHANGE_LED",
    "COIN_ACCEPTOR_POWER"
}

GPIO_INPUTS = set(GPIO_PINS.keys()) - GPIO_OUTPUTS

GPIO_INVERTED = {
    "DISPENSER_SENSOR",
    "DISPENSER_LOW",
    "MUNCHER_SENSOR",
    "MUNCHER_LOW"
}
